### ISSUE TITLE
Slashes (`/`) in redis password break URI generation

### ISSUE THREAD

**Issue by roobre** [Strech/sidekiq-prometheus-exporter#60]
If the redis password contains a forward slash (`/`), an invalid URI is generated:

```
/usr/local/lib/ruby/3.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): "redis://redis:passwordwitha/slash@redishostname:6379/0" (URI::InvalidURIError)
    from /usr/local/lib/ruby/3.2.0/uri/rfc3986_parser.rb:71:in `parse'
    from /usr/local/lib/ruby/3.2.0/uri/common.rb:193:in `parse'
    from /usr/local/bundle/gems/sidekiq-6.5.8/lib/sidekiq/redis_connection.rb:133:in `log_info'
    from /usr/local/bundle/gems/sidekiq-6.5.8/lib/sidekiq/redis_connection.rb:103:in `create'
    from /usr/local/bundle/gems/sidekiq-6.5.8/lib/sidekiq.rb:205:in `redis='
    from /app/config.ru:42:in `block (2 levels) in <main>'
    from /usr/local/bundle/gems/sidekiq-6.5.8/lib/sidekiq.rb:152:in `configure_client'
    from /app/config.ru:42:in `block in <main>'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:312:in `block in start'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:379:in `handle_profiling'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:311:in `start'
    from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:168:in `start'
    from /usr/local/bundle/gems/rack-2.2.7/bin/rackup:5:in `<top (required)>'
    from /usr/local/bundle/bin/rackup:25:in `load'
    from /usr/local/bundle/bin/rackup:25:in `<main>'
```

**Comment by roobre** [comment]
Hi @Strech, thanks for merging my PR!

I unfortunately think we need to open this, as the new image is not working as expected.

The mistake is on my part, after applying your suggestion in https://github.com/Strech/sidekiq-prometheus-exporter/pull/61/commits/7130aa84aaa0ef73d96b216a13363831619b419d I thought I properly tested the solution, but I actually tested the wrong image.

As a summary, `ERB::Util.url_encode` did escape the characters correclty, but `URI::DEFAULT_PARSER.escape`, which is currently on `main` does not: The slash still makes it unescaped, breaking the URL.

I'm not a ruby expert so I don't know which would be the best path forward here. Should we stick with `ERB::Util.url_encode`?

**Comment by roobre** [comment]
@Strech Seems to be working great now, thanks for your assistance!

**Comment by Strech** [comment]
@roobre you are welcome, and thank for your support, I appreciate it 💜
