### ISSUE TITLE
NoMethodError at /metrics undefined method `sum' for nil:NilClass

### ISSUE THREAD

**Issue by fabioaraujopt** [Strech/sidekiq-prometheus-exporter#65]
Hello guys, 

I'm having a weird error on sidekiq exporter:

```
NoMethodError: undefined method `first' for nil:NilClass
	/usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/api.rb:86:in `fetch_stats!'
	/usr/local/bundle/gems/sidekiq-6.2.1/lib/sidekiq/api.rb:11:in `initialize'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter/standard.rb:19:in `new'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter/standard.rb:19:in `initialize'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter/exporters.rb:38:in `new'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter/exporters.rb:38:in `block in to_s'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter/exporters.rb:38:in `map'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter/exporters.rb:38:in `to_s'
	/usr/local/bundle/gems/sidekiq-prometheus-exporter-0.1.15/lib/sidekiq/prometheus/exporter.rb:50:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/urlmap.rb:68:in `block in call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/urlmap.rb:53:in `each'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/urlmap.rb:53:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/tempfile_reaper.rb:15:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/lint.rb:49:in `_call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/lint.rb:37:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/show_exceptions.rb:23:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/common_logger.rb:33:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/chunked.rb:54:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/content_length.rb:15:in `call'
	/usr/local/bundle/gems/rack-2.0.9/lib/rack/handler/webrick.rb:86:in `service'
	/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

Any ideia?

**Comment by Strech** [comment]
Hi @fabioaraujopt, unfortunately, there are no guys to refer, but maintainer.

I see from your backtrace that you are using version `0.1.15` which is considered outdated and contains a mistake. Please upgrade to the latest `0.2.0` and if you are using a Docker image `strech/sidekiq-prometheus-exporter:0.2.0-4`.

**Comment by fabioaraujopt** [comment]
The update to 0.2.0-4 did work correctly. Still not quite sure about the reason, maybe the redis version? I notice we are now using redis 7 instead of 6..

**Comment by Strech** [comment]
Happy to hear that it helped 🎉
